### ISSUE TITLE
Factor out code common to Mapbox Swift libraries

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-events-ios#1]
https://github.com/mapbox/MapboxGeocoder.swift/pull/91#issuecomment-266109595 suggests factoring out a core utility library for any code that needs to be shared among MapboxGeocoder.swift, MapboxDirections.swift, and MapboxStatic.swift. It would probably end up with geometric model objects, high-level networking code, and error handling, but everything is up in the air.

@incanus and I were trying to avoid having to make these three libraries depend on additional libraries. We’re already having problems getting MapboxDirections.swift’s Polyline dependency to build on watchOS in mapbox/MapboxDirections.swift#71 for some reason. But that problem won’t go away soon, as we work on things like OSRM-text-instructions integration (mapbox/MapboxDirections.swift#101).

A core utility library would make it easier to support more Mapbox Web APIs without the overhead of keeping error handling etc. in sync among all the libraries. Eventually we do want to support all the Web APIs, and reducing that overhead would be a prerequisite. Automating releases and checking in Bitrise workflows (mapbox/MapboxGeocoder.swift#19) would also help.

An alternative proposal that floated around Mapbox was to combine all three libraries into one, similar to how our API support is centralized in [Mapbox Android/Java Services](https://github.com/mapbox/mapbox-java/), along with lots of miscellaneous code like navigation logic and geometric functions ported from Turf.js. That would avoid a proliferation of libraries, but it also means a watchOS version might be far too large if all you want is a static map.

This repository exists as a place to start factoring out a core library. If we decide down the line to glom everything into a monolithic library, the core library would be part of that merge anyways. I’ve been keeping the three repositories more or less in sync for several months, anticipating either approach.

/cc @mapbox/ios @Eldorado234 @bsudekum @tmcw

**Comment by 1ec5** [comment]
> If we decide down the line to glom everything into a monolithic library, the core library would be part of that merge anyways.

Or we could merge everything into this repository and treat it as a monorepo for multiple frameworks: #2.

**Comment by boundsj** [comment]
This repo is going to be telemetry specific so closing this now. We can copy it over to the _actual_ swift core repo when that is created.
