### ISSUE TITLE
Rewrite tests in Cedar

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-events-ios#12]
This project has used protocols and and custom fakes classes that implement those protocols to facilitate testing that requires integration with other classes the library provides and/or framework functionality. Although this has the benefit of not introducing any 3rd party testing frameworks as a project dependency, the downside is that not using a mocking framework makes the implementation more complex than it needs to be.

Since this library is written in Objective-C and because introducing a development dependency should not create any new issues with integration of this library with other SDKs and apps, we should switch to use the [Cedar](https://github.com/pivotal/cedar) testing framework. Cedar includes a test double API and also allows for a cleaner, BDD style syntax that'll make the tests in this project easier to write, read, and maintain.

**Comment by rclee** [comment]
Cedar porting complete.
