### ISSUE TITLE
Update heading orientation when device orientation changes

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-events-ios#122]
When the device’s orientation changes between portrait and landscape, we need to update any CLLocationManager’s `headingOrientation` property to reflect the new device orientation. Otherwise, headings (and course readings?) may be off by up to 90°. The map SDK [updates its location manager’s heading orientation](https://github.com/mapbox/mapbox-gl-native/blob/f3c3dc49e231208e75db64b53c5e92bb9647a661/platform/ios/src/MGLMapView.mm#L5865-L5905) whenever `-layoutSubviews` gets called on MGLMapView, since the view hierarchy is always updated on orientation changes. But this library can observe `UIDeviceOrientationDidChangeNotification`.

/ref https://github.com/mapbox/mapbox-navigation-ios/issues/1942#issuecomment-479585406
/cc @rclee

**Comment by 1ec5** [comment]
I momentarily forgot that `course` is independent of the device’s heading and therefore independent of its orientation too. Meanwhile, this library doesn’t record the heading at all, so we’re good here.

**Comment by rclee** [comment]
We're not collecting `course` at the moment either. 😄 https://github.com/mapbox/mobile-telemetry/issues/19
