### ISSUE TITLE
⚠️ Minor analyze warnings

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-events-ios#128]
Running `analyze` in the context of mapbox-gl-native, gives a few warnings:

- `- (NSError *)statusErrorFromRequest:(NSURLRequest *)request andHTTPResponse:` can return `nil`, but is marked as returning non-null.
- False positives of leaks in `reachabilityWithHostname:` & `reachabilityWithAddress:`
- Some warnings about localized strings (which IIRC are debug?)

Can we fix or mute these?

**Comment by rclee** [comment]
Thanks for reporting these @julianrex! We should really start running these checks... which has been flagged https://github.com/mapbox/mapbox-events-ios/issues/72.

@alfwatt

**Comment by julianrex** [comment]
See https://github.com/mapbox/mapbox-gl-native/pull/14572/commits/54078f68584fb3ea609962d1c0e4e51d4ac4464a - change to clean up the equivalent reachability warnings in the Maps SDK.

**Comment by alfwatt** [comment]
Done!
