### ISSUE TITLE
isReachableViaWiFi always returns YES

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/mapbox-events-ios#133]
There are multiple calls to `[[MMEReachability reachabilityForLocalWiFi] isReachableViaWiFi]` which always returns `YES` no matter if you are on WiFi or not.

@alfwatt mentioned on Slack the the correct way should be:
`[[MMEReachability reachabilityWithHostName:@"api.mapbox.com"] isReachableViaWiFi]`

**Comment by alfwatt** [comment]
Added: `+(instancetype)reachabilityForLocalWiFi MME_DEPRECATED_MSG("the resulting object isn't particularly useful");`

**Comment by alfwatt** [comment]
Use `MMEEventsManager.sharedManager.baseURL.hostname` when replacing theses
