### ISSUE TITLE
🐞 [iOS] Xcodebuild cannot build an app with MapboxMobileEvents SPM dependency

### ISSUE THREAD

**Issue by OdNairy** [mapbox/mapbox-events-ios#274]
**Configuration**
 - App Version: 1.0.0
 - SDK Version 0.10.7
 - OS Version: 11.1
 - Device: iOS Simulator
 
**Steps to Reproduce**
1. Add the latest `https://github.com/mapbox/mapbox-events-ios` as an SPM dependency in Xcode.
2. Try to build your project from Terminal for iOS Simulator:
    `xcodebuild -destination 'platform=iOS Simulator,name=iPhone 12'`
3. _Actual_: Build error `<unknown>:0: error: module map file '<REDACTED>/build/GeneratedModuleMaps-iphoneos/MapboxMobileEvents.modulemap' not found`

**Expected**
** BUILD SUCCEEDED **

**Logging**
[Sample project.zip](https://github.com/mapbox/mapbox-events-ios/files/5830492/TestSPMEventsBuild.zip)
Building from Xcode.app works correctly. The issue raises only in the xcodebuild runs.

**Comment by OdNairy** [comment]
Workaround: append `-derivedDataPath` argument with local path to the terminal command.
Note: you also have to include scheme parameter.
Sample for the attached project: `xcodebuild -destination 'platform=iOS Simulator,name=iPhone 12' -derivedDataPath derivedData/ -scheme TestSPMEventsBuild`

**Comment by frederoni** [comment]
Sample project.zip builds fine here.
```
$ unzip TestSPMEventsBuild.zip && cd TestSPMEventsBuild
$ xcodebuild -destination 'platform=iOS Simulator,name=iPhone 12'
$ ** BUILD SUCCEEDED **
```

the fact that it works for you when using a different DDP indicates that it was a cache issue to begin with.
Have you tried purging `~/Library/Developer/Xcode/DerivedData`? What version of Xcode are you using and is the same toolchain selected using xcode-select?

**Comment by OdNairy** [comment]
I have tried Xcode 12.2 and 12.3 as well as purging `~/Library/Developer/Xcode/DerivedData` with `rm -rf`. However, today I cannot reproduce that issue on my Mac. 
Originally, it was a part of an issue inside Search SDK SPM support where MapboxMobileEvents reported missing modulemap. That issues persist. 
I'll try to make a new framework with MobileEvents as a dependency. 

P.S. @don1ck reproduced the Search SDK level issue on his own mac before and after DerivedData clearance.
