### ISSUE TITLE
Map SDK helper library

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-events-ios#3]
We should create a Swift library to massage some of the Objective-Cisms in the Mapbox iOS and macOS (map) SDKs and take better advantage of Swift-only language features.

The map SDKs are written in Objective-C (at least publicly) in part because distributing binary Swift frameworks isn’t supported yet. So the most we can do to massage the API in the map SDKs themselves would be to rename some method signatures: mapbox/mapbox-gl-native#5178.

Beyond that, this helper library would:

* Turn MGLStyleValue into [an enumeration with different associated values](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Enumerations.html#//apple_ref/doc/uid/TP40014097-CH12-ID148) for constants. Imagine being able to set `MGLLineStyleLayer.lineColor` to `.constant(.black)` or `.sourceFunction(.identity, "routeColor", [.default: UIColor.black])`.
* Make the types expected by layout and paint properties more strict, taking advantage of the fact that generics in Swift don’t have to be object types. (This might conflict with the feature above.)
* Improve round-tripping of stop keys: mapbox/mapbox-gl-native#8068.

/cc @bounds @frederoni @incanus @anandthakker

**Comment by boundsj** [comment]
This repo is going to be telemetry specific so closing this now. We can copy it over to the _actual_ swift core repo when that is created.
