### ISSUE TITLE
📖 Question: Two different versioning approaches seen in Releases; clarification sought

### ISSUE THREAD

**Issue by gemmakbarlow** [mapbox/mapbox-events-ios#334]
**Link**
https://github.com/mapbox/mapbox-events-ios/releases

**Edits**

Hi folks,

From the link above, it seems as though the repo is using different release versioning systems (i.e. `v1.0.7` vs. `v10.14.0`). By looking at dates, I can see which look to be roughly equivalent, but I'd like to better understand how to map one to another. 

For context, we've ended up referencing both styles in our project, and I'd like to ensure that my update to use just one isn't introducing any new changes accidentally. 

Some documentation or tips around this would be 💯.   

- G

**Comment by vayesh** [comment]
Hi @gemmakbarlow,
Feature-wise `v1.0.x` and `v0.10.x` are the same. The difference is in the distribution model: `v0.10.x` distributed as a source dependency, so you have to build it locally, and `v1.0.x` distributed as a binary dependency.

`v1.0.x` is recommended, ex., our latest SDKs use it.
However, we are still providing updates to `v0.10.x` for customers who have not yet updated to our latest SDKs, but are interested in MME fixes.

**Comment by gemmakbarlow** [comment]
Thanks for the response @vesh93. 

To clarify, however - it doesn't seem as though `v1.0.7` would match `v0.10.7`, reading the release notes. (Let me know if I have this wrong!)

If that's the case, is the best approximation we can make between the two systems based on date ?

**Comment by vayesh** [comment]
@gemmakbarlow 
Yes, the matched versions should have the same date and similar release notes. So currently, `v1.0.7` matches `v0.10.14`.

**Comment by gemmakbarlow** [comment]
> @gemmakbarlow Yes, the matched versions should have the same date and similar release notes. So currently, `v1.0.7` matches `v0.10.14`.

Excellent, thanks for confirming.
