### ISSUE TITLE
🐞 [iOS] app is killed with signal 9 when put in background

### ISSUE THREAD

**Issue by noway** [mapbox/mapbox-events-ios#336]
**Configuration**
 - App Version: N/A
 - SDK Version: Mapbox-iOS-SDK 6.3.0
 - OS Version: 15.3.1
 - Device: iPhone 7 Plus
 
**Steps to Reproduce**
I'm using react-native-mapbox-gl and trying to play audio in background. The map is shown when the audio starts playing.

1. Start playing audio
2. Lock the phone
3. Wait about a minute or so
4. App is killed with "Message from debugger: Terminated due to signal 9" message.

I have both location and audio UIBackgroundModes yet it still happens.
<img width="506" alt="image" src="https://user-images.githubusercontent.com/2031472/159827627-2d1f7ed4-5d23-474d-8f8e-059616885946.png">

I suspect the app is killed because of the background task that MapboxMobileEvents creates. See the logs bellow.

**Expected**
1. The app not to be killed by OS

**Logging**
`
2022-03-24 11:54:31.101062+1300 myapp[8916:3189929] [BackgroundTask] Background Task 27 ("Called by MapboxMobileEvents, from -[MMEUIApplicationWrapper beginBackgroundTaskWithExpirationHandler:]"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
`

**Comment by vayesh** [comment]
@noway Could you specify the version of `MapboxMobileEvents.xcframework` you are using?

**Comment by noway** [comment]
@vesh93 I'm using version 0.10.13.

**Comment by vayesh** [comment]
@noway Thanks. There are no similar known issues for this version. I'll investigate it and get back to you.

**Comment by vayesh** [comment]
The issue is reproduced locally, looking for a fix.

**Comment by vayesh** [comment]
@noway The issue should be fixed in [v1.0.8](https://github.com/mapbox/mapbox-events-ios/releases/tag/v1.0.8). Could you please validate the fix?

**Comment by gDeep1** [comment]
@vayesh Does mapbox geofencing works when app is in terminated state? Similar to Native geofence?

**Comment by noway** [comment]
@vayesh sorry for late reply. I'm unable to validate the fix. An app code workaround was implemented instead.

But judging by the amount of time passed and no further bug reports, the fix probably worked.
