### ISSUE TITLE
UI API called from background thread (MMEEventsManager)

### ISSUE THREAD

**Issue by therobwatson** [mapbox/mapbox-events-ios#44]
I'm using Mapbox-iOS-SDK (4.0.1) which includes MapboxMobileEvents (0.4.0)
 
I'm seeing a Main Thread Checker warning triggered via -pauseOrResumeMetricsCollectionIfRequired, line 129 of MMEEventsManager.m, where checking self.application's state (MMEUIApplicationWrapper) is happening on a background thread.

![mmeeventsmanager_main-thread-checker-warning](https://user-images.githubusercontent.com/1254541/40722978-c1ad9ed6-63eb-11e8-9e51-8d1c34af599b.png)

This seems like a non-developer-facing sort of issue.  But, is there something I could be doing wrong to trigger this warning?  I'm pretty certain all my mapview-related code is executed on the main thread.

**Comment by friedbunny** [comment]
Reproduction for this issue: toggle Low Power mode from Control Center with Main Thread Checker enabled. (Hence `NSProcessInfoNotifyPowerState`.)

We should guard `MMEUIApplicationWrapper.applicationState` (and friends?) with a main thread check.

<hr>

This issue probably doesn’t lead to very many crashes, but I did encounter a mildly nonsensical one in Studio Preview (1.3.14, Mapbox iOS SDK 4.3.0-beta.1) at [`-[MGL_MMEEventsManager flush]`](https://github.com/mapbox/mapbox-events-ios/blob/397bc6fae06008c26d9f1aa7ea12a53e9ed25fdc/MapboxMobileEvents/MMEEventsManager.m#L160-L202):

> Attempting to mutate immutable collection!

```
#23. Crashed: com.apple.root.user-interactive-qos.overcommit
0  CoreFoundation                 0x181aec400 _cow_failure + 28
1  CoreFoundation                 0x181aec53c _cow_mutate_slow + 140
2  CoreFoundation                 0x181a4496c -[__NSArrayM removeAllObjects] + 160
3  Mapbox                         0x100fe52d8 -[MGL_MMEEventsManager flush] + 6660
4  Mapbox                         0x100fe50e4 -[MGL_MMEEventsManager pauseOrResumeMetricsCollectionIfRequired] + 6160
5  CoreFoundation                 0x181a50c3c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
6  CoreFoundation                 0x181a501b8 _CFXRegistrationPost + 428
7  CoreFoundation                 0x181a4ff14 ___CFXNotificationPost_block_invoke + 216
8  CoreFoundation                 0x181acd84c -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1408
9  CoreFoundation                 0x181986f38 _CFXNotificationPost + 384
10 Foundation                     0x1823f7bbc -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
11 Foundation                     0x1824ef7b8 NSProcessInfoNotifyPowerState + 172
12 libsystem_notify.dylib         0x1816d7e00 ___notify_dispatch_local_notification_block_invoke + 44
13 libdispatch.dylib              0x1813b0aa0 _dispatch_call_block_and_release + 24
14 libdispatch.dylib              0x1813b0a60 _dispatch_client_callout + 16
15 libdispatch.dylib              0x1813f24e0 _dispatch_root_queue_drain + 876
16 libdispatch.dylib              0x1813f2110 _dispatch_worker_thread3 + 112
17 libsystem_pthread.dylib        0x1816e3fac _pthread_wqthread + 1176
18 libsystem_pthread.dylib        0x1816e3b08 start_wqthread + 4
```

A supposedly mutable array ([`self.eventQueue`](https://github.com/mapbox/mapbox-events-ios/blob/397bc6fae06008c26d9f1aa7ea12a53e9ed25fdc/MapboxMobileEvents/MMEEventsManager.m#L197)), upon being `removeAllObjects`’d, failed to provide [a copy of itself for `events`](https://github.com/mapbox/mapbox-events-ios/blob/397bc6fae06008c26d9f1aa7ea12a53e9ed25fdc/MapboxMobileEvents/MMEEventsManager.m#L173) and crashed with "Attempting to mutate immutable collection!”.

Non-mutable copies of `NSMutableArray` are actually `__NSFrozenArrayM` behind the scenes — they share storage until the original is mutated (in this case, by `removeAllObjects`). I don’t see any reason for this have failed (and my reading could very well be incorrect), but threading weirdness seems like as good of answer as any.

**Comment by Karan-ios** [comment]
I'm using 'MapboxCoreNavigation' and facing folloing issue:

![Screenshot 2020-01-06 at 3 45 18 PM](https://user-images.githubusercontent.com/57385209/71811762-805f1300-309b-11ea-8e2d-290d092119b7.png)

Give me some solution to resolve!
