### ISSUE TITLE
Declare that the framework defines a module

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-events-ios#73]
With the new build system that’s on by default in Xcode 10, static frameworks are expected to set the `DEFINES_MODULE` build setting. As seen in mapbox/mapbox-navigation-ios#1748, CocoaPods now errors out if a static framework dependency doesn’t declare the setting. mapbox/mapbox-gl-native#12971 made this change in the map SDK. It should be safe for the standard way in which the navigation SDK depends on this library, but I’m not sure how it interacts with the magical way in which this library is integrated into the map SDK.

/cc @rclee @friedbunny

**Comment by frederoni** [comment]
Another report in https://github.com/mapbox/mapbox-navigation-ios/issues/1791

**Comment by paul019** [comment]
When can we expect to get an answer or an workaround to this issue? It totally prohibits to use `mapbox-navigation-ios`...
