### ISSUE TITLE
Stop shipping debug code in production library

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-events-ios#96]
This library currently ships with a variety of debug logging and a [view controller](https://github.com/mapbox/mapbox-events-ios/blob/de7f7b978b0eaa182368068aadde54fb690b4c9d/MapboxMobileEvents/MMEEventLogReportViewController.m) to view logs. Removing these developer-only features from the consumer library results in ~20-35 KB size-savings per architecture (and apparently ~400 KB for the fat, unstripped dynamic framework), based on [some rough experimentation](https://github.com/mapbox/mapbox-events-ios/compare/friedbunny-fiddles-around-with-debug-conditional-compilation):

```
$ mapbox-events-ios/scripts/check_binary_size.sh MapboxMobileEvents "MME_ENABLE_DEBUG_LOGGING=YES"
 24K	Headers
4.0K	Info.plist
3.6M	MapboxMobileEvents
564K	MapboxMobileEvents-stripped
308K	MapboxMobileEvents-stripped-arm64
260K	MapboxMobileEvents-stripped-armv7
4.0K	MapboxMobileEvents.podspec
4.0K	Modules

$ mapbox-events-ios/scripts/check_binary_size.sh MapboxMobileEvents "MME_ENABLE_DEBUG_LOGGING=NO" 
 24K	Headers
4.0K	Info.plist
3.2M	MapboxMobileEvents
496K	MapboxMobileEvents-stripped
272K	MapboxMobileEvents-stripped-arm64
240K	MapboxMobileEvents-stripped-armv7
4.0K	MapboxMobileEvents.podspec
4.0K	Modules
```

/cc @rclee @andrlee @zugaldia

**Comment by rclee** [comment]
Thanks for your foray into this @friedbunny! Certainly some burdensome code that shouldn't go to production. Hope to prioritize this soon.

**Comment by rclee** [comment]
This has been resolved. Should be shipping with a slimmer library on the next release 🎉
